# Site settings
title: Dreyer Projects
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the public face of the Dreyer brothers, Max & Jacob. 
  This website collects & ellucidates the Dreyer&rsquo;s projects to
  keep you informed and up to date. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dreyerprojects.info/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# collections
collections:
  documents:
    output: true
    permalink: /documents/:path/

# Prose settings
prose:
  rooturl: ''
  siteurl: 'http:dreyerprojects.info/'
  media: 'images'
  ignore:
    - _config.yml
    - /_layouts
    - /_includes
    - /_site
    - /images
    - /_sass
    - /css
    - /.gitignore 
    - /CNAME 
    - /feed.xml
  metadata:
    '':
      - name: "layout"
        field:
          element: "select"
          label: "Select page type"
          options:
            - name: "post"
              value: "post"
            - name: "pdf"
              value: "pdf"
            - name: "link"
              value: "link"
      - name: "categories"
        field:
          element: "select"
          label: "Select page category"
          placeholder: "...is it music or writing?"
          options:
            - name: "recordings"
              value: "recordings"
            - name: "writing"
              value: "writing"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
 
