# Site settings
title: Dreyer Projects
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the public face of the Dreyer brothers, Max & Jacob. 
  This website collects & ellucidates the Dreyer&rsquo;s projects to
  keep you informed and up to date. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dreyerprojects.info/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# collections
collections:
  documents:
    output: true
    permalink: /documents/:path/
